version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pip install -r requirements.txt
            pip install pytest-xdist pytest-cov pytest pytest-forked pluggy py mock
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
          name: Install necessary modules
      - run:
          command: |
            ./cc-test-reporter before-build
          name: Before the build
      - run:
          command: |
            pytest --cov=smok
          name: Test
      - run:
          command: |
            coverage xml
            ./cc-test-reporter after-build -t coverage.py
          name: Upload test coverage

workflows:
  main:
    jobs:
      - build-and-test
